<?php

return [
    /*
     | Environment defaults. The super admin can override provider/model/limits
     | from Admin → AI; the API key is only ever read from here or from the
     | encrypted ai_settings row, and is never returned to the dashboard.
     */
    'enabled' => (bool) env('AI_ENABLED', false),
    'provider' => env('AI_PROVIDER', 'openai'),
    'model' => env('AI_MODEL', 'gpt-5.6'),
    'base_url' => env('AI_BASE_URL'),
    'api_key' => env('AI_API_KEY'),
    'max_tokens' => (int) env('AI_MAX_TOKENS', 4000),
    'temperature' => (float) env('AI_TEMPERATURE', 0.7),
    'timeout' => (int) env('AI_TIMEOUT', 180),

    /** Generated by `pnpm blocks:catalog` from packages/blocks/src/registry.ts. */
    'block_catalog' => env('AI_BLOCK_CATALOG', resource_path('blocks/block-catalog.json')),

    'defaults' => [
        'openai' => ['base_url' => 'https://api.openai.com/v1', 'model' => 'gpt-5.6'],
        'anthropic' => ['base_url' => 'https://api.anthropic.com', 'model' => 'claude-opus-5'],
        'kimi' => ['base_url' => 'https://api.moonshot.ai/v1', 'model' => 'kimi-k2.5'],
        'openai_compatible' => ['base_url' => null, 'model' => 'gpt-5.6'],
    ],

    'models' => [
        'openai' => [
            ['id' => 'gpt-5.6', 'label' => 'GPT-5.6 (Sol)'],
            ['id' => 'gpt-5.6-sol', 'label' => 'GPT-5.6 Sol'],
            ['id' => 'gpt-5.6-terra', 'label' => 'GPT-5.6 Terra'],
            ['id' => 'gpt-5.6-luna', 'label' => 'GPT-5.6 Luna'],
            ['id' => 'gpt-4o', 'label' => 'GPT-4o'],
            ['id' => 'gpt-4o-mini', 'label' => 'GPT-4o mini'],
        ],
        'anthropic' => [
            ['id' => 'claude-opus-5', 'label' => 'Claude Opus 5'],
            ['id' => 'claude-sonnet-4-6', 'label' => 'Claude Sonnet 4.6'],
            ['id' => 'claude-3-5-sonnet-latest', 'label' => 'Claude 3.5 Sonnet'],
        ],
        'kimi' => [
            ['id' => 'kimi-k2.5', 'label' => 'Kimi K2.5'],
            ['id' => 'kimi-k3', 'label' => 'Kimi K3'],
        ],
        'openai_compatible' => [],
    ],

    'anthropic_version' => env('AI_ANTHROPIC_VERSION', '2023-06-01'),

    /** Hard ceiling on how many sections a single generated page may contain. */
    'max_sections' => (int) env('AI_MAX_SECTIONS', 14),

    /** Hard ceiling on how many pages a generated site or library template may contain. */
    'max_pages' => (int) env('AI_MAX_PAGES', 8),

    /** Extra token budget when the model is asked for a multi-page sitemap. */
    'site_max_tokens' => (int) env('AI_SITE_MAX_TOKENS', 16000),
];
