#!/bin/sh
set -e

cd /var/www/html

mkdir -p \
  /data/redis \
  /data/storage/app/public \
  /data/storage/framework/cache \
  /data/storage/framework/sessions \
  /data/storage/framework/views \
  /data/storage/logs

if [ ! -f /data/storage/.initialized ]; then
  cp -a /var/www/html/storage/. /data/storage/ 2>/dev/null || true
  touch /data/storage/.initialized
fi

rm -rf /var/www/html/storage
ln -s /data/storage /var/www/html/storage
chown -R www-data:www-data /data/storage /var/www/html/bootstrap/cache

host_from_url() {
  echo "$1" | sed -E 's#^[a-zA-Z][a-zA-Z0-9+.-]*://##' | cut -d/ -f1 | cut -d: -f1 | tr '[:upper:]' '[:lower:]'
}

platform="${PLATFORM_DOMAIN:-sites.localhost}"
preview="${PREVIEW_DOMAIN:-preview.${platform}}"
fallback="${CLOUDFLARE_FALLBACK_ORIGIN:-fallback.${platform}}"
app_host="$(host_from_url "${APP_URL:-}")"
fe_host="$(host_from_url "${FRONTEND_URL:-}")"
dashboard_hosts=""
for candidate in "$app_host" "$fe_host"; do
  case "$candidate" in
    ""|localhost|127.0.0.1) ;;
    *)
      case " $dashboard_hosts " in
        *" $candidate "*) ;;
        *) dashboard_hosts="${dashboard_hosts} ${candidate}" ;;
      esac
      ;;
  esac
done
dashboard_hosts="${dashboard_hosts# }"

mkdir -p /etc/caddy
cat > /etc/caddy/Caddyfile <<EOF
{
	auto_https off
	servers {
		trusted_proxies static 0.0.0.0/0 ::/0
	}
}

:8080 {
	encode gzip

	handle /app/* {
		reverse_proxy 127.0.0.1:8081
	}

	@backend path /api* /sanctum* /storage* /broadcasting*
	handle @backend {
		reverse_proxy 127.0.0.1:8000
	}

	@published host ${platform} *.${platform} ${preview} ${fallback}
	handle @published {
		reverse_proxy 127.0.0.1:3000 {
			header_up Host {http.request.host}
			header_up X-Forwarded-Host {http.request.host}
			header_up X-Forwarded-Proto {http.request.header.X-Forwarded-Proto}
		}
	}
EOF

if [ -n "$dashboard_hosts" ]; then
  cat >> /etc/caddy/Caddyfile <<EOF

	@dashboard host ${dashboard_hosts}
	handle @dashboard {
		root * /srv/dashboard
		try_files {path} /index.html
		file_server
	}

	handle {
		reverse_proxy 127.0.0.1:3000 {
			header_up Host {http.request.host}
			header_up X-Forwarded-Host {http.request.host}
			header_up X-Forwarded-Proto {http.request.header.X-Forwarded-Proto}
		}
	}
}
EOF
else
  cat >> /etc/caddy/Caddyfile <<EOF

	handle {
		root * /srv/dashboard
		try_files {path} /index.html
		file_server
	}
}
EOF
fi

db_port="${DB_PORT:-3306}"
db_user="${DB_USERNAME:-uidesired}"
db_password="${DB_PASSWORD:-secret}"
db_database="${DB_DATABASE:-uidesired}"

. /usr/local/bin/uplary-db.sh

run_migrations() {
  [ "${RUN_MIGRATIONS:-true}" = "true" ] || return 0

  php artisan migrate --force || return 1
  if [ "${SEED_TEMPLATES:-true}" = "true" ]; then
    php artisan db:seed --class=PlanSeeder --force || true
    php artisan db:seed --class=TemplateSeeder --force || true
  fi
  if [ "${SEED_SUPER_ADMIN:-true}" = "true" ]; then
    php artisan db:seed --class=SuperAdminSeeder --force || true
  fi
  if [ "${SEED_DEMO:-false}" = "true" ]; then
    php artisan db:seed --force || true
  fi
}

if [ -z "${APP_KEY}" ] || [ "${APP_KEY}" = "base64:" ]; then
  if [ -s /data/app-key ]; then
    APP_KEY="$(tr -d '\r\n' < /data/app-key)"
    export APP_KEY
  else
    APP_KEY="base64:$(php -r 'echo base64_encode(random_bytes(32));')"
    export APP_KEY
    printf '%s' "$APP_KEY" > /data/app-key
  fi
fi

# Booting the app builds the configured broadcaster, and Reverb's throws if its
# credentials are missing - which takes the whole API down, not just websockets.
# The app id and key are public identifiers (they ship to browsers), so they get
# fixed defaults; the secret is generated once and kept with APP_KEY.
: "${REVERB_APP_ID:=uidesired}"
: "${REVERB_APP_KEY:=uidesiredkey}"
export REVERB_APP_ID REVERB_APP_KEY

if [ -z "${REVERB_APP_SECRET}" ]; then
  if [ -s /data/reverb-secret ]; then
    REVERB_APP_SECRET="$(tr -d '\r\n' < /data/reverb-secret)"
  else
    REVERB_APP_SECRET="$(php -r 'echo bin2hex(random_bytes(16));')"
    printf '%s' "$REVERB_APP_SECRET" > /data/reverb-secret
  fi
  export REVERB_APP_SECRET
fi

# Values worked out here are exported to the supervised processes, but an
# exec'd `php artisan ...` starts from the container's own environment and would
# miss them - which used to make every manual command fail on the Reverb
# credentials. Writing them to .env gives one-off commands the same config.
# Real environment variables still win: Laravel's loader never overwrites them.
write_runtime_env() {
  umask 077
  {
    echo "# Generated by uplary-entrypoint.sh. Container env overrides these."
    echo "APP_KEY=${APP_KEY}"
    echo "REVERB_APP_ID=${REVERB_APP_ID}"
    echo "REVERB_APP_KEY=${REVERB_APP_KEY}"
    echo "REVERB_APP_SECRET=${REVERB_APP_SECRET}"
    if [ -n "${DB_HOST:-}" ]; then
      echo "DB_HOST=${DB_HOST}"
    fi
    if [ -n "${DB_PASSWORD:-}" ]; then
      echo "DB_PASSWORD=${DB_PASSWORD}"
    fi
    if [ "${DB_CONNECTION:-mysql}" = "sqlite" ] && [ -n "${DB_DATABASE:-}" ]; then
      echo "DB_DATABASE=${DB_DATABASE}"
    fi
  } > /var/www/html/.env
  chown www-data:www-data /var/www/html/.env 2>/dev/null || true

  return 0
}

write_runtime_env

php artisan config:clear --no-interaction || true
php artisan storage:link --force --no-interaction || true

if [ "${DB_CONNECTION:-mysql}" = "sqlite" ]; then
  # A single-container deployment on a panel that does not provision MySQL can
  # run entirely on SQLite. The file lives on /data so it survives redeploys.
  db_file="${DB_DATABASE:-}"
  case "$db_file" in
    :memory:) ;;
    /*) ;;
    # DB_DATABASE defaults to the MySQL name ("uidesired"), which is not a
    # usable path - turn anything relative into a file on the data volume.
    *) db_file="/data/${db_file:-uidesired}.sqlite" ;;
  esac

  if [ "$db_file" != ":memory:" ]; then
    mkdir -p "$(dirname "$db_file")"
    [ -f "$db_file" ] || : > "$db_file"
    chown www-data:www-data "$db_file" 2>/dev/null || true
  fi

  DB_DATABASE="$db_file"
  export DB_DATABASE
  echo "Using SQLite at ${db_file}."
  run_migrations || echo "Migrations failed. The app is starting anyway - check the log above."
elif [ "${DB_CONNECTION:-mysql}" = "mysql" ]; then
  db_mode="${DB_EMBEDDED:-auto}"

  # A bundled database that already holds data keeps winning. Without this, a
  # DNS hiccup on one boot would move a live deployment onto a different
  # server, and a slow external server coming back later would move it again.
  if [ "$db_mode" = "auto" ] && embedded_db_initialized; then
    db_mode=true
  fi

  if [ "$db_mode" = "true" ]; then
    if ! use_embedded_db; then
      echo "The built-in MariaDB could not be started. Check the log above." >&2
    fi
  else
    echo "Looking for the database (${DB_HOST:-db}:${db_port})..."
    if found_host="$(find_db_host)"; then
      if [ "$found_host" != "${DB_HOST:-db}" ]; then
        echo "DB_HOST was ${DB_HOST:-db}, but the database answered at ${found_host}. Using that."
      fi
      DB_HOST="$found_host"
      export DB_HOST
    elif [ "$db_mode" = "auto" ]; then
      echo "No external database answered. Falling back to the MariaDB built into this image."
      use_embedded_db || echo "The built-in MariaDB could not be started either." >&2
    fi
  fi

  if [ "$embedded_db_active" = "true" ] || [ -n "${found_host:-}" ]; then
    # A failed migration must not take the container down with it: the logs are
    # far easier to read from a running container than from a crash loop.
    run_migrations || echo "Migrations failed. The app is starting anyway - check the log above."
  else
    # Do not exit: the platform's health check only needs the web server, and a
    # container that dies here looks like a broken image rather than a database
    # that is still starting. Keep trying in the background instead.
    echo "Starting without the database. The container will restart once one answers."
    original_db_host="${DB_HOST:-db}"

    # Every boot that tries the missing host waits ~3s on DNS, and the app makes
    # a dozen connection attempts per boot - enough to push a plain health check
    # past 30s and get the container killed. Pointing at a closed local port
    # fails instantly instead, so the app stays responsive for everything that
    # does not need the database.
    DB_HOST=127.0.0.1
    export DB_HOST
    (
      while true; do
        # Quiet: the first failure already logged what went wrong and where it
        # looked, so repeating it every few seconds only buries the real logs.
        if found_host="$(find_db_host 2>/dev/null)"; then
          # The supervised processes were started with DB_HOST pointing at the
          # closed local port, and supervisor cannot rewrite the environment of
          # a running child - so they stay blind to the database no matter what
          # is exported here. Restarting is the only way to hand them the real
          # host, and it is cheap: the next boot finds the database at once.
          echo "Database reachable at ${found_host} (was ${original_db_host}); restarting the container to apply it."
          kill 1
          break
        fi
        sleep 10
      done
    ) &
  fi
else
  run_migrations
fi

# Supervisor starts its own copy of MariaDB, so the one used for provisioning
# and migrations has to let go of the data directory first.
stop_embedded_db
write_mariadb_supervisor_conf

# DB_HOST and DB_PASSWORD may have been decided since the first write.
write_runtime_env

exec "$@"
