export const productCss = `
.ud-products__open{width:100%;padding:0;border:0;cursor:pointer;font:inherit}.ud-products__title{border:0;background:none;color:inherit;font:inherit;text-align:inherit;padding:0;cursor:pointer}.ud-products__open:focus-visible,.ud-products__title:focus-visible{outline:3px solid #2563eb;outline-offset:-3px}.ud-products__open:disabled,.ud-products__title:disabled{cursor:default}.ud-products__open:hover img{transform:scale(1.03);transition:transform .2s}
.ud-product-dialog{margin:auto;inset:0;padding:0;border:0;border-radius:24px;width:min(960px,calc(100vw - 32px));max-height:90vh;overflow:auto;background:#fff;color:#171717;font:16px/1.5 system-ui,sans-serif;box-shadow:0 24px 100px #0004}.ud-product-dialog::backdrop{background:#0009}.ud-product-dialog__panel{position:relative;display:grid;grid-template-columns:1fr 1fr;gap:32px;padding:32px}.ud-product-dialog__close{position:absolute;right:12px;top:10px;z-index:2;width:36px;height:36px;border:0;border-radius:50%;background:#f0f0f0;font-size:26px;cursor:pointer}.ud-product-dialog__image{width:100%;aspect-ratio:1;object-fit:contain;border-radius:16px;background:#f5f5f5}.ud-product-dialog__placeholder{display:grid;place-items:center;aspect-ratio:1;background:#eee8df;font-size:96px;border-radius:16px}.ud-product-dialog__thumbnails{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.ud-product-dialog__thumbnails button{padding:2px;border:1px solid #ddd;background:#fff;border-radius:8px;cursor:pointer}.ud-product-dialog__thumbnails button[aria-pressed=true]{border-color:#2563eb}.ud-product-dialog__thumbnails img{width:60px;height:60px;object-fit:cover;border-radius:6px}.ud-product-dialog h2{font-size:28px;line-height:1.2;margin:12px 0}.ud-product-dialog__price{font-size:24px;font-weight:700;margin:12px 0}.ud-product-dialog__category{color:#666;text-transform:uppercase;letter-spacing:.12em;font-size:12px}.ud-product-dialog__stock{font-size:13px;color:#555}.ud-product-dialog__description{white-space:pre-line;color:#555}.ud-product-dialog__sku,.ud-product-dialog__note{font-size:12px;color:#777}.ud-product-dialog__checkout{display:grid;gap:14px;margin-top:24px}.ud-product-dialog__checkout label{display:grid;gap:6px;font-size:13px}.ud-product-dialog__checkout input{padding:12px;border:1px solid #ddd;border-radius:10px;width:100%;box-sizing:border-box;font:inherit}.ud-product-dialog__checkout button{padding:14px;border:0;border-radius:12px;background:#171717;color:white;font:inherit;font-weight:600;cursor:pointer}.ud-product-dialog__checkout button:disabled{opacity:.5;cursor:not-allowed}.ud-product-dialog__error{color:#b91c1c;font-size:13px}.ud-product-dialog__note{text-align:center;margin:0}@media(max-width:640px){.ud-product-dialog__panel{grid-template-columns:1fr;padding:24px;gap:16px}.ud-product-dialog__image{max-height:280px}}

.ud-products__intro{max-width:680px;margin-bottom:32px}.ud-products__intro .ud-lead{margin-top:12px}
.ud-products__items{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}
.ud-products__card{min-width:0;border:1px solid color-mix(in srgb,currentColor 14%,transparent);border-radius:20px;overflow:hidden;background:var(--ud-card,var(--color-surface,#fff))}
.ud-products__image{aspect-ratio:4/3;overflow:hidden;background:#eee8df;display:grid;place-items:center}.ud-products__image[data-tone="1"]{background:#e5eae3}.ud-products__image[data-tone="2"]{background:#e6e4ef}
.ud-products__image>div{width:100%;height:100%}.ud-products__image img{width:100%;height:100%;object-fit:cover}
.ud-products__placeholder{font-size:84px;font-weight:300;color:#77746f}.ud-products__body{padding:24px}.ud-products__body .ud-h3{font-size:24px;margin:0}
.ud-products__description{margin:12px 0 0;opacity:.75;white-space:pre-line}.ud-products__price{font-weight:700;font-size:20px;margin:18px 0 0}
.ud-products__empty{padding:48px 24px;text-align:center;border:1px dashed currentColor;border-radius:16px;opacity:.65}
.ud-products--featured .ud-products__items{grid-template-columns:repeat(2,minmax(0,1fr));gap:28px}
.ud-products--featured .ud-products__card{border:0;border-radius:0;background:transparent}.ud-products--featured .ud-products__image{border-radius:24px;aspect-ratio:1}.ud-products--featured .ud-products__body{padding:20px 0}
.ud-products--featured .ud-products__card:first-child{grid-row:span 2}.ud-products--featured .ud-products__card:first-child .ud-products__image{aspect-ratio:3/4}
.ud-products--list .ud-products__items{grid-template-columns:1fr;gap:0}.ud-products--list .ud-products__card{display:grid;grid-template-columns:140px 1fr;gap:24px;padding:24px 0;border:0;border-bottom:1px solid color-mix(in srgb,currentColor 14%,transparent);border-radius:0;background:transparent}.ud-products--list .ud-products__image{aspect-ratio:1;border-radius:12px}.ud-products--list .ud-products__body{padding:4px 0}
@container (max-width:760px){.ud-products__items{grid-template-columns:repeat(2,minmax(0,1fr))}}
@container (max-width:480px){.ud-products__items,.ud-products--featured .ud-products__items{grid-template-columns:1fr}.ud-products--featured .ud-products__card:first-child{grid-row:auto}.ud-products--featured .ud-products__card:first-child .ud-products__image{aspect-ratio:1}.ud-products--list .ud-products__card{grid-template-columns:88px 1fr;gap:16px}.ud-products__body .ud-h3{font-size:20px}}
`
