import type { CSSProperties, ReactNode } from 'react'
import { useState } from 'react'
import { EditableText, editOf } from '../editable'
import { Icon } from '../icons'
import { PublicForm } from '../public-form'
import { Button, Media, SafeText, SectionShell, bool, cx, items, str, type Props } from '../primitives'
import {
  ctaFields,
  descriptionField,
  eyebrowField,
  headingField,
  image,
  link,
  navLinksField,
  primaryCtaFields,
  repeater,
  schema,
  stickyField,
  text,
  textarea,
  toggle,
} from '../schema'
import { NavItem, Submenu, SubmenuCaret, hasSubmenu } from '../submenu'
import { defineBlock } from '../types'

function E({ props, path, value, as = 'span', className }: { props: Props; path: (string | number)[]; value: unknown; as?: 'span' | 'p' | 'h1' | 'h2' | 'h3' | 'h4'; className?: string }) {
  return <EditableText edit={editOf(props)} path={path} value={str(value)} as={as} className={className} />
}

function Head({ props, as = 'h2' }: { props: Props; as?: 'h1' | 'h2' }) {
  return <div className="ud-ll-head"><E props={props} path={['heading']} value={props.heading} as={as} /><E props={props} path={['accent']} value={props.accent} as="span" /></div>
}

function Kicker({ props }: { props: Props }) {
  return <E props={props} path={['eyebrow']} value={props.eyebrow} as="p" className="ud-ll-kicker" />
}

function LinkButton({ href, children, yellow = false }: { href: string; children: ReactNode; yellow?: boolean }) {
  return <a href={href} className={cx('ud-ll-button', yellow && 'is-yellow')}>{children}<Icon name="arrow" size={15} /></a>
}

const headFields = [eyebrowField, headingField, text('accent', 'Accent line'), descriptionField]

export const navbarLumen = defineBlock({
  type: 'navbar.lumen', version: 1, category: 'navigation', label: 'Lumen full-width navbar', icon: 'Menu',
  defaultProps: { brand: 'Lumen & Lane', locality: 'GREENWICH · S.E. LONDON', phone: '020 8191 4072', buttonLabel: 'Book a visit', buttonUrl: '/book', sticky: true, links: [{ label: 'Home', url: '/' }, { label: 'Services', url: '/services' }, { label: 'Pricing', url: '/pricing' }, { label: 'About', url: '/about' }, { label: 'Area', url: '/area' }, { label: 'Contact', url: '/contact' }] },
  schema: schema(text('brand', 'Brand'), text('locality', 'Locality'), text('phone', 'Phone'), ...primaryCtaFields, navLinksField('links', 'Navigation links'), stickyField),
  component: function NavbarLumen(props) {
    const [open, setOpen] = useState(false)
    return <header className={cx('ud-ll-nav', bool(props.sticky, true) && 'is-sticky')}><div className="ud-ll-nav__inner">
      <a href="/" className="ud-ll-brand"><b>↯</b><span><E props={props} path={['brand']} value={props.brand} /><small><E props={props} path={['locality']} value={props.locality} /></small></span></a>
      <nav className={cx(open && 'is-open')}>{items(props.links, []).map((item, i) => <NavItem key={i} item={item}><a href={str(item.url, '#')}><E props={props} path={['links', i, 'label']} value={item.label} /><SubmenuCaret show={hasSubmenu(item)} /></a><Submenu props={props} item={item} index={i} /></NavItem>)}</nav>
      <a className="ud-ll-phone" href={`tel:${str(props.phone).replace(/\s/g, '')}`}><Icon name="phone" size={15} /><E props={props} path={['phone']} value={props.phone} /></a>
      <LinkButton href={str(props.buttonUrl, '/book')} yellow><E props={props} path={['buttonLabel']} value={props.buttonLabel} /></LinkButton>
      <button className="ud-ll-nav__toggle" onClick={() => setOpen(!open)} aria-label="Toggle navigation"><Icon name={open ? 'close' : 'menu'} size={21} /></button>
    </div></header>
  },
})

export const heroLumen = defineBlock({
  type: 'hero.lumen', version: 1, category: 'hero', label: 'Lumen framed photo hero', icon: 'Image',
  defaultProps: { eyebrow: 'LOCAL ELECTRICAL HELP', heading: 'Power restored,', accent: 'without the runaround.', description: 'Careful domestic and small-business electrical work across Greenwich and nearby South-East London.', image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=2400&q=88', buttonLabel: 'Book a visit', buttonUrl: '/book', secondaryLabel: 'See services', secondaryUrl: '/services', tall: false },
  schema: schema(...headFields, image('image', 'Background image'), ...ctaFields, toggle('tall', 'Tall hero', 'layout')),
  component: (props) => <SectionShell props={props} bleed className={cx('ud-ll-hero', bool(props.tall) && 'is-tall')} style={{ backgroundImage: `linear-gradient(90deg,rgba(1,6,25,.82),rgba(1,6,25,.18)),url(${str(props.image)})` } as CSSProperties}><div className="ud-ll-hero__copy"><Kicker props={props} /><Head props={props} as="h1" /><SafeText value={str(props.description)} className="ud-ll-lead" edit={editOf(props)} path={['description']} /><div className="ud-ll-actions"><LinkButton href={str(props.buttonUrl, '/book')} yellow><E props={props} path={['buttonLabel']} value={props.buttonLabel} /></LinkButton><LinkButton href={str(props.secondaryUrl, '/services')}><E props={props} path={['secondaryLabel']} value={props.secondaryLabel} /></LinkButton></div></div></SectionShell>,
})

export const servicesLumen = defineBlock({
  type: 'services.lumen', version: 1, category: 'services', label: 'Lumen service card grid', icon: 'Grid',
  defaultProps: { eyebrow: 'SERVICES', heading: 'Everyday electrical work,', accent: 'finished properly.', description: 'From a tripping circuit to new lighting, each visit starts with a clear scope and likely cost.', cardCtaLabel: 'Book this service', cardCtaUrl: '/book', filters: [{ label: 'Homes & flats' }, { label: 'Small businesses' }], cards: [
    { tag: 'HOME', title: 'Fault finding', description: 'Tracing trips, dead rooms and mystery faults methodically.', price: 'From £88', image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=84' },
    { tag: 'HOME', title: 'Sockets & switches', description: 'Replacements, upgrades and neat new positions.', price: 'From £58', image: 'https://images.unsplash.com/photo-1558449033-2cf3a28a92e4?auto=format&fit=crop&w=900&q=84' },
    { tag: 'HOME', title: 'Lighting installation', description: 'Pendants, wall lights, dimmers and garden lighting.', price: 'From £76', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=84' },
    { tag: 'SAFETY', title: 'Consumer unit checks', description: 'RCD testing and clear advice on upgrades.', price: 'From £98', image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=900&q=84' },
    { tag: 'LANDLORD', title: 'EICR certificates', description: 'Full reports for rental properties, delivered promptly.', price: 'From £145', image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=84' },
    { tag: 'ENERGY', title: 'EV charging checks', description: 'Installation support and safety checks for home chargers.', price: 'From £155', image: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=900&q=84' },
  ] },
  schema: schema(...headFields, text('cardCtaLabel', 'Card CTA label'), link('cardCtaUrl', 'Card CTA URL'), repeater('filters', 'Audience filters', [text('label', 'Label')], { itemLabel: 'Filter' }), repeater('cards', 'Service cards', [text('tag', 'Tag'), text('title', 'Title'), textarea('description', 'Description'), text('price', 'Starting price'), image('image', 'Image')], { itemLabel: 'Service' })),
  component: function ServicesLumen(props) { const [active, setActive] = useState(0); return <SectionShell props={props} className="ud-ll-services"><div className="ud-ll-wide"><div className="ud-ll-centered"><Kicker props={props} /><Head props={props} /><SafeText value={str(props.description)} className="ud-ll-copy" edit={editOf(props)} path={['description']} /><div className="ud-ll-segments">{items(props.filters, []).map((item, i) => <button className={i === active ? 'is-active' : ''} onClick={() => setActive(i)} key={i}><E props={props} path={['filters', i, 'label']} value={item.label} /></button>)}</div></div><div className="ud-ll-services__grid">{items(props.cards, []).map((card, i) => <article key={i}><div className="ud-ll-services__image"><Media src={str(card.image)} alt={str(card.title)} ratio="wide" edit={editOf(props)} path={['cards', i, 'image']} /><span><E props={props} path={['cards', i, 'tag']} value={card.tag} /></span><b><E props={props} path={['cards', i, 'price']} value={card.price} /></b></div><div><h3><E props={props} path={['cards', i, 'title']} value={card.title} /></h3><SafeText value={str(card.description)} className="ud-ll-copy" edit={editOf(props)} path={['cards', i, 'description']} /><a href={str(props.cardCtaUrl, '/book')}><E props={props} path={['cardCtaLabel']} value={str(props.cardCtaLabel, 'Book this service')} /> <Icon name="arrow" size={14} /></a></div></article>)}</div></div></SectionShell> },
})

export const valuesLumen = defineBlock({
  type: 'features.lumen', version: 1, category: 'features', label: 'Lumen values and statistics', icon: 'Shield',
  defaultProps: { eyebrow: 'WHY PEOPLE CALL BACK', heading: 'Small details', accent: 'make a safer job.', description: 'Clear communication matters as much as careful installation.', stats: [{ value: '14+', label: 'Years in the trade' }, { value: '1,900+', label: 'Local jobs completed' }, { value: '4.9', label: 'Average customer rating' }], values: [{ icon: 'shield', title: 'Fully qualified', description: 'Certified, insured and current with regulations.' }, { icon: 'map-pin', title: 'Truly local', description: 'One small team working in one area.' }, { icon: 'tag', title: 'Clear pricing', description: 'Likely cost agreed before work begins.' }, { icon: 'sparkles', title: 'Tidy finish', description: 'Floors protected and rooms left clean.' }, { icon: 'message-circle', title: 'Plain English', description: 'Useful explanations without jargon.' }, { icon: 'home', title: 'Home aware', description: 'Respectful work around families and pets.' }] },
  schema: schema(...headFields, repeater('stats', 'Statistics', [text('value', 'Value'), text('label', 'Label')], { itemLabel: 'Statistic' }), repeater('values', 'Values', [text('icon', 'Icon'), text('title', 'Title'), textarea('description', 'Description')], { itemLabel: 'Value' })),
  component: (props) => <SectionShell props={props} className="ud-ll-values"><div className="ud-ll-wide ud-ll-values__grid"><div><Kicker props={props} /><Head props={props} /><SafeText value={str(props.description)} className="ud-ll-copy" edit={editOf(props)} path={['description']} /><div className="ud-ll-stats">{items(props.stats, []).map((item, i) => <div key={i}><strong><E props={props} path={['stats', i, 'value']} value={item.value} /></strong><E props={props} path={['stats', i, 'label']} value={item.label} as="p" /></div>)}</div></div><div className="ud-ll-values__cards">{items(props.values, []).map((item, i) => <article key={i}><Icon name={str(item.icon, 'check')} size={20} /><h3><E props={props} path={['values', i, 'title']} value={item.title} /></h3><SafeText value={str(item.description)} className="ud-ll-copy" edit={editOf(props)} path={['values', i, 'description']} /></article>)}</div></div></SectionShell>,
})

export const pricingLumen = defineBlock({
  type: 'pricing.lumen', version: 1, category: 'pricing', label: 'Lumen transparent price list', icon: 'CreditCard',
  defaultProps: { eyebrow: 'GUIDE PRICES', heading: 'Useful starting points,', accent: 'not mystery invoices.', description: 'Every job is confirmed before it begins. These are realistic guide prices for common local work.', guideNote: 'Guide prices for local work. Your scope is confirmed before the visit.', promises: [{ title: 'Quote first', description: 'Know the likely cost before tools come out.' }, { title: 'Local visits', description: 'No inflated travel charge inside our core area.' }, { title: 'Parts explained', description: 'Standard parts included; larger items quoted.' }, { title: 'Landlord friendly', description: 'Batch visits available for several properties.' }], services: [{ title: 'Socket or switch replacement', description: 'Per fitting, standard parts included.', price: '£58' }, { title: 'Light fitting installation', description: 'Pendants, spots and wall lights.', price: '£76' }, { title: 'Consumer unit inspection', description: 'Visual check and RCD testing.', price: '£98' }, { title: 'Landlord electrical report', description: 'Full EICR for a flat or small house.', price: '£145' }, { title: 'Small commercial visit', description: 'Shops, cafés and compact offices.', price: '£105' }] },
  schema: schema(...headFields, text('guideNote', 'Guide-price note'), repeater('promises', 'Pricing promises', [text('title', 'Title'), textarea('description', 'Description')], { itemLabel: 'Promise' }), repeater('services', 'Guide prices', [text('title', 'Service'), textarea('description', 'Description'), text('price', 'Price')], { itemLabel: 'Service' })),
  component: (props) => <SectionShell props={props} className="ud-ll-pricing"><div className="ud-ll-wide"><div className="ud-ll-centered"><Kicker props={props} /><Head props={props} /><SafeText value={str(props.description)} className="ud-ll-copy" edit={editOf(props)} path={['description']} /></div><div className="ud-ll-pricing__grid"><div>{items(props.promises, []).map((item, i) => <article key={i}><Icon name="check" size={16} /><div><h3><E props={props} path={['promises', i, 'title']} value={item.title} /></h3><SafeText value={str(item.description)} className="ud-ll-copy" edit={editOf(props)} path={['promises', i, 'description']} /></div></article>)}</div><div>{items(props.services, []).map((item, i) => <article key={i}><Icon name="zap" size={17} /><div><h3><E props={props} path={['services', i, 'title']} value={item.title} /></h3><SafeText value={str(item.description)} className="ud-ll-copy" edit={editOf(props)} path={['services', i, 'description']} /></div><strong><E props={props} path={['services', i, 'price']} value={item.price} /></strong></article>)}<aside><Icon name="info" size={18} /> <E props={props} path={['guideNote']} value={str(props.guideNote, 'Guide prices for local work. Your scope is confirmed before the visit.')} /></aside></div></div></div></SectionShell>,
})

export const aboutLumen = defineBlock({
  type: 'content.lumen_about', version: 1, category: 'content', label: 'Lumen local story', icon: 'Columns',
  defaultProps: { eyebrow: 'A SMALL INDEPENDENT TEAM', heading: 'Experienced hands,', accent: 'familiar streets.', description: 'Lumen & Lane was started by an electrician who wanted to make home repairs feel simpler: arrive when promised, explain the options, and leave everything safe and neat.', image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1400&q=86', imageAlt: 'Local electrician at work', buttonLabel: 'Meet the team', buttonUrl: '/about', cards: [{ title: 'On the tools', description: 'Fourteen years across domestic wiring, safety checks and thoughtful upgrades.' }, { title: 'Off the clock', description: 'Usually near Greenwich Park, coffee in hand, answering one last message.' }] },
  schema: schema(...headFields, image('image', 'Portrait or work image'), text('imageAlt', 'Image alt'), ...primaryCtaFields, repeater('cards', 'Story cards', [text('title', 'Title'), textarea('description', 'Description')], { itemLabel: 'Card' })),
  component: (props) => <SectionShell props={props} className="ud-ll-about"><div className="ud-ll-wide"><div className="ud-ll-about__hero"><div><Kicker props={props} /><Head props={props} as="h1" /><SafeText value={str(props.description)} className="ud-ll-lead" edit={editOf(props)} path={['description']} /><LinkButton href={str(props.buttonUrl, '/about')} yellow><E props={props} path={['buttonLabel']} value={props.buttonLabel} /></LinkButton></div><Media src={str(props.image)} alt={str(props.imageAlt)} ratio="portrait" edit={editOf(props)} path={['image']} /></div><div className="ud-ll-about__cards">{items(props.cards, []).map((item, i) => <article key={i}><h3><E props={props} path={['cards', i, 'title']} value={item.title} /></h3><SafeText value={str(item.description)} className="ud-ll-copy" edit={editOf(props)} path={['cards', i, 'description']} /></article>)}</div></div></SectionShell>,
})

export const areaLumen = defineBlock({
  type: 'content.lumen_area', version: 1, category: 'content', label: 'Lumen service-area gallery', icon: 'Map',
  defaultProps: { eyebrow: 'OUR PATCH', heading: 'One local zone,', accent: 'covered properly.', description: 'Working close to home keeps arrival windows honest and repeat visits easy.', mapImage: 'https://images.unsplash.com/photo-1564594736624-def7a10ab047?auto=format&fit=crop&w=1400&q=82', places: [{ name: 'Greenwich', code: 'SE10', note: 'Home base · same-week visits', image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=900&q=84' }, { name: 'Blackheath', code: 'SE3', note: 'Homes, flats and studios', image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=900&q=84' }, { name: 'Deptford', code: 'SE8', note: 'Independent shops and cafés', image: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=84' }, { name: 'Lewisham', code: 'SE13', note: 'Family homes and rentals', image: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=900&q=84' }], roads: [{ label: 'Trafalgar Road' }, { label: 'Blackheath Hill' }, { label: 'Deptford High Street' }, { label: 'Lee Road' }, { label: 'Creek Road' }, { label: 'Lewisham Way' }] },
  schema: schema(...headFields, image('mapImage', 'Map image'), repeater('places', 'Neighbourhood cards', [text('name', 'Place'), text('code', 'Postcode'), text('note', 'Note'), image('image', 'Image')], { itemLabel: 'Place' }), repeater('roads', 'Road chips', [text('label', 'Road')], { itemLabel: 'Road' })),
  component: (props) => <SectionShell props={props} className="ud-ll-area"><div className="ud-ll-wide"><div className="ud-ll-area__top"><div><Kicker props={props} /><Head props={props} as="h1" /><SafeText value={str(props.description)} className="ud-ll-copy" edit={editOf(props)} path={['description']} /><Media src={str(props.mapImage)} alt="Service area map" ratio="wide" edit={editOf(props)} path={['mapImage']} /></div><div className="ud-ll-area__places">{items(props.places, []).map((item, i) => <article key={i}><Media src={str(item.image)} alt={str(item.name)} ratio="square" edit={editOf(props)} path={['places', i, 'image']} /><div><h3><E props={props} path={['places', i, 'name']} value={item.name} /></h3><small><E props={props} path={['places', i, 'code']} value={item.code} /></small><E props={props} path={['places', i, 'note']} value={item.note} as="p" /></div></article>)}</div></div><div className="ud-ll-roads">{items(props.roads, []).map((item, i) => <span key={i}><Icon name="map-pin" size={13} /><E props={props} path={['roads', i, 'label']} value={item.label} /></span>)}</div></div></SectionShell>,
})

export const contactLumen = defineBlock({
  type: 'form.lumen_contact', version: 1, category: 'form', label: 'Lumen contact workspace', icon: 'Mail',
  defaultProps: { eyebrow: 'GET IN TOUCH', heading: 'Tell us what', accent: 'needs sorting.', description: 'Share the essentials and we will come back with the clearest next step.', phoneLabel: 'CALL', emailLabel: 'EMAIL', hoursLabel: 'HOURS', phone: '020 8191 4072', email: 'hello@lumenlane.co.uk', hours: 'Mon–Fri 08:00–18:00 · Sat 09:00–14:00', formId: '', submitLabel: 'Send message', mapImage: 'https://images.unsplash.com/photo-1564594736624-def7a10ab047?auto=format&fit=crop&w=1200&q=80' },
  schema: schema(...headFields, text('phoneLabel', 'Phone label'), text('phone', 'Phone'), text('emailLabel', 'Email label'), text('email', 'Email'), text('hoursLabel', 'Hours label'), text('hours', 'Working hours'), text('formId', 'Connected form ID'), text('submitLabel', 'Submit label'), image('mapImage', 'Map image')),
  component: (props) => <SectionShell props={props} className="ud-ll-contact"><div className="ud-ll-wide"><div className="ud-ll-centered"><Kicker props={props} /><Head props={props} as="h1" /><SafeText value={str(props.description)} className="ud-ll-copy" edit={editOf(props)} path={['description']} /></div><div className="ud-ll-contact__grid"><aside><div><span><E props={props} path={['phoneLabel']} value={str(props.phoneLabel, 'CALL')} /></span><strong><E props={props} path={['phone']} value={props.phone} /></strong></div><div><span><E props={props} path={['emailLabel']} value={str(props.emailLabel, 'EMAIL')} /></span><strong><E props={props} path={['email']} value={props.email} /></strong></div><div><span><E props={props} path={['hoursLabel']} value={str(props.hoursLabel, 'HOURS')} /></span><strong><E props={props} path={['hours']} value={props.hours} /></strong></div><Media src={str(props.mapImage)} alt="Local service area" ratio="wide" edit={editOf(props)} path={['mapImage']} /></aside><PublicForm formId={str(props.formId) || undefined} submitLabel={str(props.submitLabel)} edit={editOf(props)} submitLabelPath={['submitLabel']} fields={[{ name: 'name', label: 'Name', type: 'text', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'phone', label: 'Phone', type: 'phone' }, { name: 'postcode', label: 'Postcode', type: 'text' }, { name: 'message', label: 'How can we help?', type: 'textarea', required: true }]} /></div></div></SectionShell>,
})

export const bookingLumen = defineBlock({
  type: 'form.lumen_booking', version: 1, category: 'form', label: 'Lumen booking form', icon: 'Calendar',
  defaultProps: { eyebrow: 'BOOK ONLINE', heading: 'Request a local', accent: 'electrical visit.', description: 'Choose the closest service, add the useful details, and we will confirm a practical arrival window.', formId: '', submitLabel: 'Request my appointment', progressLabel: 'BOOKING PROGRESS', tips: [{ title: 'Choose a service', description: 'Pick the closest match—you can explain more below.' }, { title: 'Add the details', description: 'A postcode and a short description are enough.' }, { title: 'We confirm', description: 'You will receive a reply with a date and arrival window.' }] },
  schema: schema(...headFields, text('formId', 'Connected form ID'), text('submitLabel', 'Submit label'), text('progressLabel', 'Progress heading'), repeater('tips', 'Booking steps', [text('title', 'Title'), textarea('description', 'Description')], { itemLabel: 'Step' })),
  component: (props) => <SectionShell props={props} className="ud-ll-book"><div className="ud-ll-wide"><div className="ud-ll-centered"><Kicker props={props} /><Head props={props} as="h1" /><SafeText value={str(props.description)} className="ud-ll-copy" edit={editOf(props)} path={['description']} /></div><div className="ud-ll-book__grid"><aside><span><E props={props} path={['progressLabel']} value={str(props.progressLabel, 'BOOKING PROGRESS')} /></span>{items(props.tips, []).map((item, i) => <article key={i}><i>{String(i + 1).padStart(2, '0')}</i><div><h3><E props={props} path={['tips', i, 'title']} value={item.title} /></h3><SafeText value={str(item.description)} className="ud-ll-copy" edit={editOf(props)} path={['tips', i, 'description']} /></div></article>)}</aside><PublicForm formId={str(props.formId) || undefined} submitLabel={str(props.submitLabel)} edit={editOf(props)} submitLabelPath={['submitLabel']} fields={[{ name: 'name', label: 'Name', type: 'text', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'phone', label: 'Phone', type: 'phone' }, { name: 'service', label: 'What do you need?', type: 'select', options: ['Fault or power issue', 'Socket or switch', 'Lighting', 'Safety check', 'Landlord report', 'Other'] }, { name: 'postcode', label: 'Postcode', type: 'text' }, { name: 'project', label: 'Job description', type: 'textarea', required: true }]} /></div></div></SectionShell>,
})

export const ctaLumen = defineBlock({
  type: 'cta.lumen', version: 1, category: 'cta', label: 'Lumen centered call to action', icon: 'MousePointerClick',
  defaultProps: { eyebrow: 'READY WHEN YOU ARE', heading: 'Not sure what', accent: 'to book?', description: 'Send a few details and we will point you in the right direction—no pressure.', buttonLabel: 'Book a visit', buttonUrl: '/book', secondaryLabel: 'Send a message', secondaryUrl: '/contact' },
  schema: schema(...headFields, ...ctaFields),
  component: (props) => <SectionShell props={props} className="ud-ll-cta"><div className="ud-ll-centered"><Kicker props={props} /><Head props={props} /><SafeText value={str(props.description)} className="ud-ll-copy" edit={editOf(props)} path={['description']} /><div className="ud-ll-actions"><LinkButton href={str(props.buttonUrl, '/book')}><E props={props} path={['buttonLabel']} value={props.buttonLabel} /></LinkButton><a href={str(props.secondaryUrl, '/contact')}><E props={props} path={['secondaryLabel']} value={props.secondaryLabel} /> <Icon name="arrow" size={14} /></a></div></div></SectionShell>,
})

export const footerLumen = defineBlock({
  type: 'footer.lumen', version: 1, category: 'footer', label: 'Lumen oversized footer', icon: 'PanelBottom',
  defaultProps: { brand: 'Lumen & Lane', locality: 'GREENWICH ELECTRICIANS', description: 'Independent electrical help for homes, landlords and small businesses across South-East London.', phone: '020 8191 4072', email: 'hello@lumenlane.co.uk', address: 'Greenwich, London SE10', copyright: '© 2026 Lumen & Lane · Fully qualified · Fully insured', buttonLabel: 'Book a visit', buttonUrl: '/book', exploreLabel: 'EXPLORE', contactLabel: 'GET IN TOUCH', bookLabel: 'BOOK A VISIT', bookNote: 'Choose a time online. It takes about a minute.', links: [{ label: 'Services', url: '/services' }, { label: 'Pricing', url: '/pricing' }, { label: 'About', url: '/about' }, { label: 'Area', url: '/area' }, { label: 'Contact', url: '/contact' }] },
  schema: schema(text('brand', 'Brand'), text('locality', 'Locality'), textarea('description', 'Description'), text('phone', 'Phone'), text('email', 'Email'), text('address', 'Address'), text('copyright', 'Copyright'), text('exploreLabel', 'Links column label'), text('contactLabel', 'Contact column label'), text('bookLabel', 'Book column label'), textarea('bookNote', 'Book column note'), ...primaryCtaFields, repeater('links', 'Footer links', [text('label', 'Label'), link('url', 'URL')], { itemLabel: 'Link' })),
  component: (props) => <footer className="ud-ll-footer"><div className="ud-ll-footer__word"><E props={props} path={['brand']} value={props.brand} /></div><div className="ud-ll-wide ud-ll-footer__grid"><div><div className="ud-ll-brand"><b>↯</b><span><E props={props} path={['brand']} value={props.brand} /><small><E props={props} path={['locality']} value={props.locality} /></small></span></div><SafeText value={str(props.description)} className="ud-ll-copy" edit={editOf(props)} path={['description']} /></div><nav><span><E props={props} path={['exploreLabel']} value={str(props.exploreLabel, 'EXPLORE')} /></span>{items(props.links, []).map((item, i) => <a href={str(item.url, '#')} key={i}><E props={props} path={['links', i, 'label']} value={item.label} /></a>)}</nav><div><span><E props={props} path={['contactLabel']} value={str(props.contactLabel, 'GET IN TOUCH')} /></span><p><E props={props} path={['phone']} value={props.phone} /></p><p><E props={props} path={['email']} value={props.email} /></p><p><E props={props} path={['address']} value={props.address} /></p></div><div><span><E props={props} path={['bookLabel']} value={str(props.bookLabel, 'BOOK A VISIT')} /></span><p><E props={props} path={['bookNote']} value={str(props.bookNote, 'Choose a time online. It takes about a minute.')} /></p><LinkButton href={str(props.buttonUrl, '/book')} yellow><E props={props} path={['buttonLabel']} value={props.buttonLabel} /></LinkButton></div></div><div className="ud-ll-wide ud-ll-footer__base"><E props={props} path={['copyright']} value={props.copyright} /></div></footer>,
})
